# Generated by Django 4.1 on 2022-08-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
